### GET request to example server
GET http://localhost:8080/getMap

### Insert a new node
POST http://localhost:8080/insert
Content-Type: application/json

{
  "id": 123,
  "address": "localhost:8081"
}
