version: '3.8'

services:
  storage1:
    image: storage:1.0
    environment:
      - PORT=10000
      - ROLE=STORAGE
    ports:
      - "10001:10000"

  storage2:
    image: storage:1.0
    environment:
      - PORT=10000
      - ROLE=STORAGE
    ports:
      - "10002:10000"
    command: sh -c "sleep 2 && /storage"

  storage3:
    image: storage:1.0
    environment:
      - PORT=10000
      - ROLE=STORAGE
    ports:
      - "10003:10000"
    command: sh -c "sleep 2 && /storage"
  queue1:
    image: queue:1.0
    environment:
      - PORT=9000
      - ROLE=QUEUE
    ports:
      - "10005:9000"

  queue2:
    image: queue:1.0
    environment:
      - PORT=9000
      - ROLE=QUEUE
    ports:
      - "10006:9000"
    command: sh -c "sleep 2 && /queue"

  init:
    image: busybox
    command: sh -c "sleep 1"